workspace:
  base: /go
  path: src/github.com/karantin2020/tmplr

pipeline:
  test1.9:
    # group: tests
    image: golang:1.9-alpine3.7
    commands:
      - apk update && apk add git
      - go get -u -v github.com/jawher/mow.cli
      - go get -u -v github.com/karantin2020/fasttemplate
      - go build -ldflags="-s -w" -v -o tmplr
      - ./tmplr -v
      - go generate -v
      - diff ./tmp/IntStr.go ./tmp/IntStr.go.go
      
  test1.10:
    # group: tests
    image: golang:1.10-alpine3.7
    commands:
      - apk update && apk add git
      - go get -u -v github.com/jawher/mow.cli
      - go get -u -v github.com/karantin2020/fasttemplate
      - go build -ldflags="-s -w" -v -o tmplr
      - ./tmplr -v
      - go generate -v
      - diff ./tmp/IntStr.go ./tmp/IntStr.go.go